version: '2'
services:
  nginx:
   container_name: v-nginx
   image: nginx:1.13
   restart: always
   ports:
   - 80:80
   - 443:443
   volumes:
   - ./nginx/conf.d:/etc/nginx/conf.d
    
  mysql:
   container_name: v-mysql
   image: mysql/mysql-server:5.7
   environment:
    MYSQL_DATABASE: test
    MYSQL_ROOT_PASSWORD: root
    MYSQL_ROOT_HOST: '%'
   ports:
   - "3306:3306"
   restart: always
    
  app-x:
    restart: always
    build: ./app
    working_dir: /app
    volumes:
      - ./app:/app
      - ~/.m2:/root/.m2
#expose port to linked containers but not host.
    expose:
      - "8080"
    depends_on:
      - nginx
      - mysql
#Any @Component or @Configuration can be marked with @Profile to limit when it is loaded.
#https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-profiles.html
    command: mvn clean spring-boot:run -Dspring-boot.run.profiles=docker
